### ISSUE TITLE
Example env.sh

### ISSUE THREAD

**Issue by GabrielCC** [GoogleCloudPlatform/fourkeys#109]
In multiple parts of the project, an `env.sh` file is referenced.
I think an example of the file should be provided, to simplify the full setup and later usages.

**Comment by dinagraves** [comment]
Hi Gabriel, 

Thank you for this issue!  The `env.sh` is autogenerated by the setup script - we wouldn't expect anyone to create it outside of that process.  We've update the documentation to try to make the use of the `env.sh` file a little clearer.  https://github.com/GoogleCloudPlatform/fourkeys/pull/112

Please let us know if this is still confusing or if you have any other questions!
-Dina
