### ISSUE TITLE
Move from Scheduled Queries to Materialized Views

### ISSUE THREAD

**Issue by dinagraves** [GoogleCloudPlatform/fourkeys#130]
Requirement: 
- All dashboard tables stored in Materialized Views
- Scripts managed in version control
- Use terraform to create instead of bash

**Comment by davidstanke** [comment]
There's a branch for this: `bigquery_views`, but it's blocked on #155

**Comment by davidstanke** [comment]
We're actually going with regular (non-materialized) views... this change is included in PR #160
