### ISSUE TITLE
Dataset query returned no results

### ISSUE THREAD

**Issue by Ustarroz** [GoogleCloudPlatform/fourkeys#152]
Hi,
I'm struggling since yesterday to setup a new project.  I Faced the Google authentication problem and followed the advice given in issue [86](https://github.com/GoogleCloudPlatform/fourkeys/issues/86).

But even after that, my dashboard were empty, I did some research and after some time I have found that my querys were returning no results. 
I see no particular errors in logs and workers are successfully triggered when I send Mock data

<img width="1380" alt="Screenshot 2021-06-30 at 14 42 47" src="https://user-images.githubusercontent.com/18734826/123962168-7167d100-d9b1-11eb-9d00-9149f2239378.png">

It's been some hours now and I'm drying out of ideas, would you have any guess on what's happening ?

**Comment by dinagraves** [comment]
Do you have rows in `four_keys.events_raw`?    When you look at the Scheduled Queries tab, do you see 3 scheduled queries for incidents, changes, and deployments?

**Comment by Ustarroz** [comment]
Yes to all, I have the 3 scheduled queries for incident, changes and deployment
<img width="1126" alt="Screenshot 2021-07-01 at 09 20 44" src="https://user-images.githubusercontent.com/18734826/124083341-0ae4c080-da4e-11eb-8492-24716df4dbad.png">
I also see that I have rows in the four_keys.events_raw
<img width="1432" alt="Screenshot 2021-07-01 at 09 22 08" src="https://user-images.githubusercontent.com/18734826/124083472-2d76d980-da4e-11eb-9b3e-6b10b792e091.png">

**Comment by dinagraves** [comment]
Are they still empty?  Are they all empty or is it just the incidents table?

**Comment by dinagraves** [comment]
If it's only the incidents table, it was probably fixed by https://github.com/GoogleCloudPlatform/fourkeys/pull/151.   Could you try re-running the data generator?  https://github.com/GoogleCloudPlatform/fourkeys#generating-mock-data

**Comment by Ustarroz** [comment]
I checked this morning and yes it seems that the mock data finally showed up 
<img width="1341" alt="Screenshot 2021-07-02 at 13 33 25" src="https://user-images.githubusercontent.com/18734826/124268650-17464780-db3a-11eb-8df3-979645f72907.png">
I understand that those scheduled query are responsible to send the data every 24h ? So there was maybe no problem in the end. Sorry for the inconvenience !

**Comment by dinagraves** [comment]
No problem!  We're going to transition to views which will be more real time. Glad it's working!
