### ISSUE TITLE
Connector color code time to restore vs lead time to change

### ISSUE THREAD

**Issue by jomw10** [GoogleCloudPlatform/fourkeys#157]
It seems the same keys are used for time to restore and lead to time to change, but the color code associated are not the same.
For example, a less than one week lead time to change should be green (as per color coding in fourkeys project) while a less than one week time to restore should be yellow.  Same occurs with One day (purple vs green), One week (green vs yellow), One month (yellow vs red). Also I don't see a value for 6 months (red).

**Comment by dinagraves** [comment]
We're now using Grafana instead of DataStudio.  This issue is now obsolete.
