### ISSUE TITLE
Move Unit Tests & Linting to GitHub Actions

### ISSUE THREAD

**Issue by dinagraves** [GoogleCloudPlatform/fourkeys#162]
Cloud Build is opaque.  Contributors should be able to see their tests running / failing and all the details included.  GitHub Actions has better visibility.

**Comment by rethab** [comment]
Hey @dinagraves if you're open to outside contributions, this might be something I could help with :)

**Comment by davidstanke** [comment]
Ooh, that'd be great!

**Comment by davidstanke** [comment]
Also note #143 -- let's put any new CI config into a `ci` folder.

**Comment by dinagraves** [comment]
+1 that would be wonderful! Thank you!

**Comment by rethab** [comment]
@davidstanke is it important that the new folder is called `ci`? For GitHub Actions, the build files are usually placed in `.github`.

**Comment by davidstanke** [comment]
Ah, good point @rethab --- yes, do that! :)
