### ISSUE TITLE
Fix deprecation warning for itsdangerous.json

### ISSUE THREAD

**Issue by davidstanke** [GoogleCloudPlatform/fourkeys#164]
When running nox tests: `DeprecationWarning: Importing 'itsdangerous.json' is deprecated and will be removed in ItsDangerous 2.1. Use Python's 'json' module instead.`

**Comment by iennae** [comment]
@davidstanke did this potentially get resolved with this https://github.com/GoogleCloudPlatform/fourkeys/pull/275 since it looks like the reason you did that PR was related to a problem you saw https://github.com/GoogleCloudPlatform/fourkeys/issues/274

**Comment by rogerthatdev** [comment]
Checked latest tests and looks like this deprecation warning is no more.

@davidstanke if this is incorrect please reopen.
