### ISSUE TITLE
setup fails to add fake data to the incidents table

### ISSUE THREAD

**Issue by wpannell** [GoogleCloudPlatform/fourkeys#165]
> Thanks for reporting! Did you run this as part of the setup script or separately?

Both.

> Have the scheduled queries updated since you ran the generate data script?

Yes.  And, I forced on-demand runs on GCP to check my sanity.  I also repeated the setup process from scratch several times.

> Please let me know if this did not solve your issue and there is another bug! Feel free to reopen!

I originally cloned the repo on `6/4` and I was on  `Google Cloud SDK [342.0.0]`.  I did not see this problem.

I cloned a fresh repo on the date I reported this issue and I upgraded to the latest version of the Google Cloud SDK.

I think this is a real bug that was introduced during that interim.

_Originally posted by @wpannell in https://github.com/GoogleCloudPlatform/fourkeys/issues/153#issuecomment-877514160_

**Comment by dinagraves** [comment]
Thanks!  Just merged in a fix: https://github.com/GoogleCloudPlatform/fourkeys/pull/160/files#diff-059b54476054cc148c27950fb6e3399d0701c9172f084a36f5dddf66877ff440

LMK if that addresses the issue!

**Comment by wpannell** [comment]
Wow. (lol) Quick. Responsive.

I had just rolled back to confirm things worked correctly before and was going to post a screenshot to demonstrate.

I'll let you know one way of the other after I roll forward to the trunk revision of the repo.
