### ISSUE TITLE
For e2e tests, build containers in Cloud Build

### ISSUE THREAD

**Issue by davidstanke** [GoogleCloudPlatform/fourkeys#167]
e2e tests will probably run faster if we build the [event-handler,data parsers] containers as Cloud Build steps in the e2e testing pipeline, rather than invoking separate Cloud Build executions from bash.

- add parallelized steps to `e2e_tests_terraform.cloudbuild.yaml` that build the containers
- add a flag to `install.sh` to skip container builds (this will also be useful for testing the terraform install from local)

**Comment by dinagraves** [comment]
My only comment here is that I want to ensure that we're testing the flow as close as possible to the real one.

**Comment by davidstanke** [comment]
> My only comment here is that I want to ensure that we're testing the flow as close as possible to the real one.

That's a very good point. Let's not.
