### ISSUE TITLE
Create Decision Records

### ISSUE THREAD

**Issue by dinagraves** [GoogleCloudPlatform/fourkeys#169]
https://adr.github.io/

- Containers
- Views vs Scheduled Queries
- Dashboard
- Webhook
- Multiple Pub/Sub topics
- Terraform
- ETL in the worker vs the view / scheduled query
- Levels of views / union'ing tables

**Comment by rogerthatdev** [comment]
We may reopen this when a roadmap is confirmed that will include decision records.
