### ISSUE TITLE
time to restore service badge shows null

### ISSUE THREAD

**Issue by wpannell** [GoogleCloudPlatform/fourkeys#173]
When instrumenting a new repository, the `Time to Restore` service badge shows null:

![2021-07-22_07-19-40](https://user-images.githubusercontent.com/2018993/126655637-e6a7e425-49b4-45d2-aefa-fd6c993566e0.png)

**Comment by dinagraves** [comment]
We've launched a new dashboard in Grafana! Check it out! https://github.com/GoogleCloudPlatform/fourkeys/tree/main/dashboard
