### ISSUE TITLE
App blocked error when trying to connect data to dashboard

### ISSUE THREAD

**Issue by FPDuarte** [GoogleCloudPlatform/fourkeys#184]
Hi,
I ran the setup script and it finished successfully with a message requesting me to visit datastudio.google.com.
I navigated to the site and an authorization was required (Data Studio requires authorization to use this community connector.). I authorized but I got a pop-up from Google saying:

This app is blocked
This app tried to access sensitive info in your Google Account. To keep your account safe, Google blocked this access.

Any on how to prevent Google from block this request?

Regards,
Flavio

**Comment by dinagraves** [comment]
Hi Flavio!  I'm so sorry about that -- this is a known issue.  Please see workaround here: https://github.com/GoogleCloudPlatform/fourkeys/issues/86#issuecomment-823574890
