### ISSUE TITLE
add sql function null-check to terraform

### ISSUE THREAD

**Issue by davidstanke** [GoogleCloudPlatform/fourkeys#187]
#186 fixes an error condition in the JSON2Array custom SQL function. That change needs to be applied here as well: https://github.com/GoogleCloudPlatform/fourkeys/blob/1acf0046dadde324f6a267859616064573ac73c8/experimental/terraform/resource_bigquery.tf#L44

**Comment by dinagraves** [comment]
Thank you, Dave!  I assumed the terraform would read in the definitions from the SQL files?

**Comment by davidstanke** [comment]
Nah, it has to be formatted in a very specific way (as I learned from a long sequence of failures!)

**Comment by davidstanke** [comment]
(Although, if we were to separate out _just_ the function body, we could read that in as a file to the terraform config. But IDK how to do, like, an include file within a SQL command. Is that a thing?)

**Comment by dinagraves** [comment]
Bummer.   Can we create a 2nd copy for terraform and just delete the first one once the shell setup goes away?

**Comment by dinagraves** [comment]
Should we add a test condition for this?  This passed in the e2e tests because the deployments were not null.

**Comment by davidstanke** [comment]
> Bummer. Can we create a 2nd copy for terraform and just delete the first one once the shell setup goes away?

Yep, we can do that. It's consistent with the way we import the sql queries into the tf setup.

**Comment by davidstanke** [comment]
> Should we add a test condition for this? This passed in the e2e tests because the deployments were not null.

Tests are good! Though this one's a bit tricky b/c we'd have to do an incomplete setup in order to test that things work with no deployments (then do a proper setup and test that). I'd like to say this is more of a unit-test case, but since it's SQL, well, probably not. So IMHO it's not worth the complexity. WDYT?
