### ISSUE TITLE
FR: Create tool to trigger the scheduled scripts on demand

### ISSUE THREAD

**Issue by dinagraves** [GoogleCloudPlatform/fourkeys#20]
Currently if you want to re-run the scripts that populate the derived tables, you have to find the query history and execute it again manually.  We should have an easy python script or set of gcloud commands to run the scripts and update the tables.

**Comment by dmitri-lerko** [comment]
[Scheduling queries](https://cloud.google.com/bigquery/docs/scheduling-queries) can be a very good fit for this.

**Comment by dinagraves** [comment]
Thanks! I found just the [method](https://cloud.google.com/bigquery-transfer/docs/reference/datatransfer/rest/v1/projects.locations.transferConfigs/startManualRuns) to use!  We already use the transfer config [here](https://github.com/GoogleCloudPlatform/fourkeys/blob/master/queries/schedule.py), so I'll build on that.

**Comment by dinagraves** [comment]
Running schedule.py will now execute the query for you
