### ISSUE TITLE
Show the dashboard in the README

### ISSUE THREAD

**Issue by nathenharvey** [GoogleCloudPlatform/fourkeys#21]
Adding a screenshot of the dashboard that includes the sample data will help users understand visualize the end state and motivate them to go through the process of setting up the dashboard.

**Comment by michelleirvine** [comment]
This is being addressed in https://github.com/GoogleCloudPlatform/fourkeys/pull/55

**Comment by dinagraves** [comment]
Fixed in https://github.com/GoogleCloudPlatform/fourkeys/pull/55
