### ISSUE TITLE
Add dashboard connectivity check to e2e tests

### ISSUE THREAD

**Issue by davidstanke** [GoogleCloudPlatform/fourkeys#222]
In addition to verifying that the bigquery tables are populated, let's add a check to confirm that the dashboard URL can be accessed and returns a 200 status.

(?) is it possible [without using some sort of fragile screen scraping ickiness] to validate that the contents of the dashboard are correct?

**Comment by dinagraves** [comment]
Yes!  There is an API!  I assume you can use the API to read in some values.
