### ISSUE TITLE
Deployments object seems not to have additional_sha in its fields

### ISSUE THREAD

**Issue by gkuga** [GoogleCloudPlatform/fourkeys#224]
Hi, thank you for this grate project. I am about to use this to improve delivery performance.
I'm thinking about the matter related to #50.
https://github.com/GoogleCloudPlatform/fourkeys/blob/01d9eba79667780215a73dad1e36349dca862449/queries/deployments.sql#L11-L13
I think there is no additional_sha field in [Deployments object](https://docs.github.com/en/graphql/reference/objects#deployment).
So we have to put those in payload field and retrieve those with following sql for example:
```sql
CASE WHEN source LIKE "github%" THEN JSON_VALUE_ARRAY(JSON_VALUE(metadata, '$.deployment.payload'), '$.additional_sha')
```
If there is anything that I overlooked, please point them out.

**Comment by dinagraves** [comment]
Hi Gaku,

`additional_sha` was a custom field that a user suggested adding to the payload to include additional information in the deployment data sent to the webhook.  The user set up a script to send that information using the data from `git log ...` .  It does not come default from GitHub.  

Please let me know if you have any other questions!
Dina
