### ISSUE TITLE
Send Webhook events to the event-handler

### ISSUE THREAD

**Issue by wulfland** [GoogleCloudPlatform/fourkeys#241]
I'm using GitHub Actions as a CI/CD platform and I want to sent webhook events to the dashboard when I deploy to different stages. 

Under [Collecting Deployment Data](https://github.com/GoogleCloudPlatform/fourkeys/tree/main/setup#collecting-deployment-data) I can find:

> For whichever CI/CD system you are using, set it up to send Webhook events to the event-handler.

But I can't find any documentation on how to do that. Do you have a simple example?

[Question][Documentation]

**Comment by wulfland** [comment]
By the way: the new terraform deployment is awesome! I could set up the dashboard really fast and it worked great! Thanks for the great job!

**Comment by wulfland** [comment]
May my question is not too clear. I don't really care about the event handler if I can filter the data any other way. But right now I only can send all data to the event handler. But not every GitHub action that runs is a deployment. And not every commit is a change. Is there a way to configure what counts as a deployment and what es a change? Like the convention with the `Incident` tag maybe?

**Comment by davidstanke** [comment]
You may find this interesting: [New database design (proposed)](https://github.com/GoogleCloudPlatform/fourkeys/discussions/240) -- I'd love to get your feedback on that!

**Comment by dinagraves** [comment]
Hi there!  Sorry for the late response here.  I would recommend doing this filter in the SQL scripts.  If you edit [this query](https://github.com/GoogleCloudPlatform/fourkeys/blob/main/queries/changes.sql) and re-apply the Terraform, then it should pick up the new query in the BigQuery views.  Using tags to do the filtering is a great idea!
