### ISSUE TITLE
SVG logo needed to add 4 Keys to CDF Landscape

### ISSUE THREAD

**Issue by MarckK** [GoogleCloudPlatform/fourkeys#252]
Hi 4 Keys!

We at the CDF are big fans and would like to add the 4 Keys project to the CDF Landscape. 

To do so, we need a 4 Keys SVG logo. 

We have a [WIP of where 4 Keys will likely go the CDF Landscape](https://github.com/cdfoundation/cdf-landscape/pull/203).

Currently, 4 Keys is placed under the 'Observability and Analysis: DevOps Metrics' category, and has a temporary Jenkins X logo, while we wait for 4 keys logo.

If you would like to propose a different category name, now is a good time to do so 😀
Also, if any of the 4 Keys data is incorrect (beyond logo), please comment on the WIP.

For SVG logo, you can add it via PR to [the CDF landscape repo](https://github.com/cdfoundation/cdf-landscape).

**Comment by dinagraves** [comment]
Happy New Year!  

David is working on a logo and we'll send it over shortly!

**Comment by MarckK** [comment]
Wonderful!  

Happy New Year! 🥳

**Comment by davidstanke** [comment]
Thank you Kara! I opened https://github.com/cdfoundation/cdf-landscape/pull/211 to add the SVG logo.

**Comment by MarckK** [comment]
Thank you @davidstanke and @dinagraves! 
New svg and edits have been added to 4 Keys landscape card.
You can see the new additions on the landscape: https://landscape.cd.foundation/

Sorry for the slow reply, I was away at a study residential. :)
