### ISSUE TITLE
issue webhooks from gitlab are not stored in the database.

### ISSUE THREAD

**Issue by vincentvanrijn** [GoogleCloudPlatform/fourkeys#253]
Hi fourkeys, I found an issue in the software: webhooks from gitlab, triggered by an gitlab issue, are not stored in the database. In the log I see this warning:
```
debugInfo: ""
location: "time_created"
message: "Could not parse '2021-12-23 11:26:21 +0100' as a timestamp. Required format is YYYY-MM-DD HH:MM[:SS[.SSSSSS]]"
reason: "invalid"
```
Could you please investigate what’s going wrong?

(Possible solution could be to create a timestamp if a timestamp parse exeption is thrown)

**Comment by dinagraves** [comment]
The good news is that the events are not lost - they should stay in pub/sub until they're successfully posted to the parser and ingested into BigQuery. 

Unfortunately, it looks like Gitlab has updated some of the timestamp formats to this timezone format, which BigQuery doesn't recognize natively.  We will add a function into the parser to fix this.  Thank you for reporting!

**Comment by dinagraves** [comment]
I've updated the gitlab-parser.  Please re-deploy the Cloud Run service with the updated code.  LMK if you have any questions!
