### ISSUE TITLE
No data in deployments table . Data is present in events_raw table. I am using gitlab for VCS and CI/CD 

### ISSUE THREAD

**Issue by kevin-vakayil** [GoogleCloudPlatform/fourkeys#254]
deployments table with no data (no mock data is used here , Runned pipeline and tested it manually)
<img width="298" alt="dep 4 keys" src="https://user-images.githubusercontent.com/87632641/147938172-be57c80f-144c-4914-afb8-fa7e8797af24.png">

events table has data 
<img width="343" alt="even" src="https://user-images.githubusercontent.com/87632641/147938424-1d21c6b8-7936-4734-8300-c386ac935690.png">

**Comment by dinagraves** [comment]
What are the other event_types in your events_raw?  A `push` wouldn't be a deployment -- are there pipeline or deployment types in the table?

**Comment by kevin-vakayil** [comment]
There seems to be only push event_type in the events_raw table, I redeployed four_keys still I am getting the same error

**Comment by kevin-vakayil** [comment]
> 

There seems to be only push event_type in the events_raw table, I redeployed four_keys still I am getting the same error

**Comment by kevin-vakayil** [comment]
I reran the project again and it worked fine

**Comment by dinagraves** [comment]
Probably related to https://github.com/GoogleCloudPlatform/fourkeys/pull/256. -- Some of the timestamps from GitLab have migrated to a different format and BigQuery wasn't recognizing them.

**Comment by kevin-vakayil** [comment]
I am mow  facing a issue simmilar to #256 I will mention it in a new issue with the details And thanks for the fast update with the isuues.
