### ISSUE TITLE
Incidents table is not showing data in BigQuery for fourkeys Gitlab(VCS and CI/CD). It is displaying the following "Invalid timestamp: '2022-01-05 04:36:28 -0800'"

### ISSUE THREAD

**Issue by kevin-vakayil** [GoogleCloudPlatform/fourkeys#257]
The Incidents table data is not currently displaying in Big Query and is returning with Invalid timestamp: '2022-01-05 04:36:28 -0800'.
I am using Gitlab for both VCS and CI/CD.

<img width="500" alt="time stamp issue" src="https://user-images.githubusercontent.com/87632641/148332658-f8adf87e-d3df-44c5-9d64-31544d7e467d.png">

<img width="398" alt="time stamp issue incident table" src="https://user-images.githubusercontent.com/87632641/148332672-fdc49b8b-22b2-4c93-a725-79fd74d08f3d.png">

When I looked in to the events_raw table the metadata from GitLab is having timestamps with timezone information.I have seen similar issue in #256 . The incidents table is also having similar issue.

<img width="739" alt="ev2" src="https://user-images.githubusercontent.com/87632641/148336062-6d28e28f-a958-48d5-8f4f-0e6ad259b4b0.png">

Can you please fix this issue?

**Comment by dinagraves** [comment]
Thank you for reporting!  Issue requires a quick SQL fix -- we need to use the `PARSE_TIMESTAMP` function instead of the `TIMESTAMP` function, since it isn't recognized by default.
