### ISSUE TITLE
Slack Link in Contributing Doc not working

### ISSUE THREAD

**Issue by ranael-garem** [GoogleCloudPlatform/fourkeys#260]
Trying out the slack link in the docs is not working. Not entirely sure if this is an open invitation, apologies if it is not

https://github.com/GoogleCloudPlatform/fourkeys/blob/main/CONTRIBUTING.md#discussion

**Comment by dinagraves** [comment]
It is an open invitation!  I'll look into it! So sorry!

**Comment by dinagraves** [comment]
Resolved! Thank you!
