### ISSUE TITLE
Note events from gitlab show error

### ISSUE THREAD

**Issue by vincentvanrijn** [GoogleCloudPlatform/fourkeys#263]
Note event from gitab are not stored correctly in Incidents table

When I query the table the following error is shown:

invalidQuery: Failed to parse input string "2022-01-12T09:47:26.948+01:00". 

This error is also in the Grafana dashboard

**Comment by dinagraves** [comment]
To confirm -- the events are being stored properly in the `events_raw` table?

**Comment by vincentvanrijn** [comment]
I will check this tomorrow.

**Comment by vincentvanrijn** [comment]
Yes. The note event is store in the events_raw table.

**Comment by JRShearer81** [comment]
what is the event in what is a raw table and if the table is raw is it made
of meat and does need to be cooked

**Comment by dinagraves** [comment]
Thanks for that info -- gitlab timestamps continue to be challenging!  We're working on a function to clean all the timestamps in the downstream queries.

**Comment by dinagraves** [comment]
https://github.com/GoogleCloudPlatform/fourkeys/pull/266 should fix this.  LMK if you still have issues!
