### ISSUE TITLE
github-parser does not get attributes from mock data generator

### ISSUE THREAD

**Issue by saschakiefer** [GoogleCloudPlatform/fourkeys#267]
Hi all,

after I successfully deployed the tool to GCP, there were no mock data in the db table.
After some research I found out, that the event handler is called and successfully generates the message in `pubsub`. This message is also pushed to the github handler. However there an exception is raised (`Missing pubsub attributes`).

I added some debug statements in the cloud run services. The `event-handler` sends the following header to `pubsub` :
```JSON
{
  "Host": "event-handler-<id>-ew.a.run.app",
  "Content-Length": "289",
  "X-Github-Event": "issues",
  "X-Hub-Signature": "sha1=<signature>",
  "User-Agent": "GitHub-Hookshot/mock",
  "Content-Type": "application/json",
  "Mock": "True",
  "X-Cloud-Trace-Context": "<number>",
  "Traceparent": "<number>",
  "X-Forwarded-For": "<ip>",
  "X-Forwarded-Proto": "https",
  "Forwarded": "for=\"<ip>\";proto=https",
  "Accept-Encoding": "identity"
}
```

but the `github-parser` only receives
```JSON
{
  "message": {
    "data": "eyJpc3N1ZSI6eyJjcmVhdGVkX2F0IjoiVGVzdCBNZXNzYWdlIiwidXBkYXRlZF9hdCI6IjIwMjItMDEtMzFUMTM6Mzk6MDdaIiwiY2xvc2VkX2F0IjoiMjAyMi0wMS0zMVQxMzozOTowN1oiLCJudW1iZXIiOiIxMjM0IiwibGFiZWxzIjpbeyJuYW1lIjoiSW5jaWRlbnQifV0sImJvZHkiOiJyb290IGNhdXNlOiAzNDQzMmEzNDVqajUiLCJyZXBvc2l0b3J5Ijp7Im5hbWUiOiJmb29iYXIifX19",
    "messageId": "<id>",
    "message_id": "<id>",
    "publishTime": "2022-02-01T12:47:58.315Z",
    "publish_time": "2022-02-01T12:47:58.315Z"
  },
  "subscription": "projects/<project_id>/subscriptions/github-subscription"
}
```

Did anyone else ever experienced that. Unfortunately I'm sort of stuck. I could change the code and all, but I think this must be a different issue. 

Thanks, and best regards,
Sascha

**Comment by dinagraves** [comment]
Thank you for reporting, Sascha!   I'm wondering if something has changed on the Pub/Sub side.  We're looking into it!

**Comment by dinagraves** [comment]
We're not able to reproduce the bug.  If you're available, we have office hours today and also in a couple weeks.  You could try to deploy again?  Are you deploying from Head?  Using the terraform installer? 

If that doesn't work, could you create a pull subscription in pub/sub subscribed to the github topic, regenerate some mock events, and take a look at the messages.   You should see attributes in the message:
<img width="415" alt="Screen Shot 2022-02-01 at 1 56 50 PM" src="https://user-images.githubusercontent.com/55413432/152032899-db664f04-99b8-442a-ab06-95a068ad787d.png">

**Comment by saschakiefer** [comment]
Hi Dina, thanks for the quick reply 👍

Very nice trick with the pull subscriber. That at least showed me, that the messages had attributes.

I did not re-deploy the whole solution but manually deleted the `github` subscriber and ran `terraform apply` which redeployed just the subscriber. Strangely after that it worked.

Thanks again for the support.
