### ISSUE TITLE
Service Unavailable while Generating Data

### ISSUE THREAD

**Issue by Sbhalsing0** [GoogleCloudPlatform/fourkeys#282]
Getting service unavailable error while generating mock data.
The event-handler parser is not working, Can you please suggest how to resolve this issue??

![fourkeys_error](https://user-images.githubusercontent.com/42617962/159662320-c19b9ddd-2d03-43ef-9c13-3f9b467ba70b.JPG)

**Comment by davidstanke** [comment]
Hi! That's unintended. :) I'm not sure what's going on here, but if you'd like to debug it together, you should join us at our biweekly office hours (next one is Apr 12): https://github.com/GoogleCloudPlatform/fourkeys/blob/main/CONTRIBUTING.md#office-hours

Hope to see you there!

**Comment by rogerthatdev** [comment]
Try generating data outside of the set-up script:

1. Set environment variables for WEBHOOK and SECRET
2. From root of repo, run: python data_generator/generate_data.py --vc_system=github
