### ISSUE TITLE
Datastudio dashboard template

### ISSUE THREAD

**Issue by mclalchandani** [GoogleCloudPlatform/fourkeys#29]
I can't seem to figure out the Datastudio Dashboard template step here. Launching the Datastudio URL, it gives me a message "The linked connectorid was invalid". 

I also tried looking for a template in Datastudio community but can't find any similar.

**Comment by dinagraves** [comment]
Hello there!  

We're working on getting the connector published so it's more easily accessible.  In the meantime, I've shared all the scripts for the charts here: https://github.com/GoogleCloudPlatform/fourkeys/blob/main/METRICS.md

**Comment by davidstanke** [comment]
Duplicate of #86
