### ISSUE TITLE
Error Posting from event_handler to github parser

### ISSUE THREAD

**Issue by sethjones** [GoogleCloudPlatform/fourkeys#315]
Hello,
I have deployed the latest version of the repo towards my gcp infrastructure, and am seeing an interesting error in the logs of the event_handler service.  No data is being passed to bigquery due to this error.  

I am using the python data generator to test these services.

"errors: Failed to find specversion in HTTP request, json_payload"

Has anyone seen this?

**Comment by dinagraves** [comment]
I remember seeing something like this a long time ago.   I believe it was environmental.  What OS are you using?  What python version are you using?

**Comment by dinagraves** [comment]
If this is the same thing, setting this flag fixes it: `PYTHONHTTPSVERIFY=0`

**Comment by sethjones** [comment]
I'm running python 3.9 on macos 12.3.

I attempted to add this env to the github and event_handler image, and it doesnt appear to have resolved it.

**Comment by sethjones** [comment]
I found an error on my end, and was deploying the wrong image to the github service... whoooops
