### ISSUE TITLE
How to setup on local linux environment or dockerized environment?

### ISSUE THREAD

**Issue by jaythamke** [GoogleCloudPlatform/fourkeys#32]
Hi Dina,

I have attended your Four Keys presentation during cdCon2020. I liked the tool. I would like to know if it is possible to run the dashboard on the local setup? I would move it to GCP later. Thanks

regards,
Jayesh

**Comment by donmccasland** [comment]
The dashboard only runs in datastudio.  As far as I know, there is no way to run DataStudio in a local environment.

**Comment by dinagraves** [comment]
Hi Jayesh, 

The data is in BigQuery and I've published the scripts used for the dashboard in the new metrics documentation: [METRICS.md](https://github.com/GoogleCloudPlatform/fourkeys/blob/main/METRICS.md)

You should be able to use these scripts with any SQL based dashboard system.

Thanks!
Dina
