### ISSUE TITLE
Tests for Terraform changes

### ISSUE THREAD

**Issue by rogerthatdev** [GoogleCloudPlatform/fourkeys#335]
We need automated tests for changes to Terraform

**Comment by davidstanke** [comment]
Make E2E tests for new module-ized Terraform installer.

**Comment by davidstanke** [comment]
#338 adds an E2E test for new module-based terraform installer. It fully destroys and recreates the 4keys infra. We should _also_ add an e2e test which performs an in-place upgrade.
