### ISSUE TITLE
Automatic issue/PR labeling

### ISSUE THREAD

**Issue by Wyatt-Stanke** [GoogleCloudPlatform/fourkeys#342]
You can use [this cool official GitHub action](https://github.com/github/issue-labeler) and [this other official one](https://github.com/actions/labeler) to automatically label issues and pull requests. This will help a lot with organization.

**Comment by rogerthatdev** [comment]
Thank you for the suggestion! We've got some internal processes in place for triaging and labeling issues on this repo.
