### ISSUE TITLE
Data connector details are missing

### ISSUE THREAD

**Issue by jgrumboe** [GoogleCloudPlatform/fourkeys#42]
This issue is just for the record. (sorry, to push you @dinagraves)
Would be cool to get more insight into the data connector and how it crunshes numbers. 😀

**Comment by dinagraves** [comment]
Thank you for creating the bug!

**Comment by dgrenner** [comment]
I found a partial work-around until this is resolved. If you use the view in Data Studio (using the connector), the queries that are run will show up in BigQuery's history. Opening those queries up will show how the queries are made.

**Comment by dinagraves** [comment]
To get the datastudio connector to work nicely, I had to combine all the metrics into one franken-script.  I'm planning on adding a page to the documentation explaining each individual part of it.

**Comment by dinagraves** [comment]
Hello!  

Wanted to update the bug - I'm still working on getting the connector published, but we've shared all the scripts here: https://github.com/GoogleCloudPlatform/fourkeys/blob/main/METRICS.md

**Comment by dinagraves** [comment]
Connector details are now mirrored under the [connector/](https://github.com/GoogleCloudPlatform/fourkeys/tree/main/connector) directory!
