### ISSUE TITLE
Should the PubSub topic created for `"google_pubsub_topic"` be named `cloud-builds`?

### ISSUE THREAD

**Issue by grahamalama** [GoogleCloudPlatform/fourkeys#423]
Currently, if the `cloud-build` parser is enabled, [one of the resources created](https://github.com/GoogleCloudPlatform/fourkeys/blob/9e04246183bc8bbd854467262c1f6a7526dfcdfb/terraform/modules/fourkeys-cloud-build-parser/main.tf#L47) is a PubSub topic named `cloudbuild`.

In the [docs](https://cloud.google.com/build/docs/configuring-notifications/notifiers#cloud_build-notifiers) for Cloud Build notifiers however, it reads:

> Cloud Build sends all build event updates, along with build metadata, to Pub/Sub on the `cloud-builds` topic.

Does this mean that the terraform block should look something like:
```tf
resource "google_pubsub_topic" "cloudbuild" {
  project = var.project_id
  name    = "cloud-builds"
}
```
?

I haven't fully tested this yet, but before I did, I was wondering if this was intentional before I investigated further.

**Comment by rogerthatdev** [comment]
Hi, 

Thanks for the feedback.  The pubsub topic that's created in the fourkeys module isn't meant to refer to the Cloud Build notifiers written about in the documentation, it's only meant to serve as the topic used by the cloud build parser, similar to those created for the other parsers (for example, see [gitlab](https://github.com/GoogleCloudPlatform/fourkeys/blob/9e04246183bc8bbd854467262c1f6a7526dfcdfb/terraform/modules/fourkeys-gitlab-parser/main.tf#L49) and [github](https://github.com/GoogleCloudPlatform/fourkeys/blob/9e04246183bc8bbd854467262c1f6a7526dfcdfb/terraform/modules/fourkeys-github-parser/main.tf#L49)).
