### ISSUE TITLE
Rename `master` to `main`

### ISSUE THREAD

**Issue by davidstanke** [GoogleCloudPlatform/fourkeys#64]
Looks like [it just got easier](https://github.blog/changelog/2021-01-19-support-for-renaming-an-existing-branch/) -- any reason we shouldn't proceed? @dinagraves @donmccasland

**Comment by dinagraves** [comment]
Thumbs up!

We just need to make sure we update the Cloud Build triggers in the testing project.   And maybe take another look at the Tekton worker - but I don't *think* there is any branch logic in it.

**Comment by davidstanke** [comment]
Assigning to Dina since she has the most context on Cloud Build and Tekton (LMK if I can help).

**Comment by dinagraves** [comment]
Done
