### ISSUE TITLE
setup.sh gcloud command flag order may be incorrect

### ISSUE THREAD

**Issue by davezen1** [GoogleCloudPlatform/fourkeys#65]
I noticed in some places where gcloud is run that flags are not after the command:

For example:  

`export WEBHOOK=$(gcloud run --platform managed --region ${FOURKEYS_REGION} services describe event-handler --format=yaml | grep url | head -1 | sed -e 's/  *url: //g')`

Running the above, I get this error: 

`ERROR: (gcloud.run) unrecognized arguments: --platform (did you mean '--format'?)

To search the help text of gcloud commands, run:
  gcloud help -- SEARCH_TERMS`

Modifications that seem to work: 

`  export WEBHOOK=$(gcloud run services describe event-handler --platform managed --region ${FOURKEYS_REGION} --format=yaml | grep url | head -1 | sed -e 's/  *url: //g')`

**Comment by davidstanke** [comment]
Hi @davezen1 ! Thanks for the report. I _think_ this may have been fixed with the changes in #57 -- can you try again and report back?

**Comment by davezen1** [comment]
Yes, ran it with the latest code and it is fixed.

**Comment by davidstanke** [comment]
Great, thanks for the update!
