### ISSUE TITLE
Update requirements.txt for event_handler

### ISSUE THREAD

**Issue by davidstanke** [GoogleCloudPlatform/fourkeys#74]
The requirements file for event_handler includes the lines:
```
pytest==5.3.0; python_version > "3.0"
pytest==4.6.6; python_version < "3.0"
```

...since we require python >= 3.6, and since pytest is now at version 6, I propose we update this to:
```
pytest~=6.0.0
```
Does that sound okay to you, @dinagraves 

(this is what I'm using for the event_handler tests)

Also, we could get faster installs and slimmer prod builds if we isolate testing dependencies. AIUI, PIP doesn't support "dev dependencies" like e.g. npm, but I did find this: https://stackoverflow.com/questions/17803829/how-to-customize-a-requirements-txt-for-multiple-environments

**Comment by dinagraves** [comment]
Excellent point.  In python-docs-samples, we have two files: requirements.txt and requirements-test.txt.  I propose we do the same for fourkeys.
