### ISSUE TITLE
Add more data to dashboard screenshot

### ISSUE THREAD

**Issue by dinagraves** [GoogleCloudPlatform/fourkeys#77]
Add more data to show in the README and the METRICS.md.

**Comment by davidstanke** [comment]
(As you're likely aware:) The data generator script now supports [optional parameters](https://github.com/GoogleCloudPlatform/fourkeys/blob/d945489865135c8f200a2f8f32ceb8e2c94ff94d/data_generator/generate_data.py#L30-L36) to change the timespan in which events are generated, and the number of changes/issues created.
