### ISSUE TITLE
How to integrate Jira as issue/bug tracker and change failure source?

### ISSUE THREAD

**Issue by jgrumboe** [GoogleCloudPlatform/fourkeys#80]
Hi,

We are using Jira instead of Github issues to track our bugs or change failures. What could be a good way to integrate Jira as source?
As a metric we could use the time between opening and resolving a Jira issue with type bug (in our case).
I was thinking about polling Jira once daily to import all issues with a specific type "bug" into the four_keys "incidents" table directly. I guess we would need to deactivate the scheduled query for incidents since it would truncate other created entries.
What do you think?

BR, Jo

**Comment by dinagraves** [comment]
Ah great question!  Does Jira have a webhook option? If so, then it would be a good idea to use the same structure as the other integrations.  I have some high level instructions here on how to do that: https://github.com/GoogleCloudPlatform/fourkeys#extending-to-other-event-sources

If you would prefer polling, I suggest adding to the `four_keys.events_raw` table rather than directly to the `incidents` table.  This way you maintain the table as a log of all your devops events!  It also then becomes easier to include / exclude things downstream without losing the data.

**Comment by jgrumboe** [comment]
Thanks for your reply. 
I think Jira has webhook notification support but only Jira Administratora can configure these as far as I know, and unfortunately/luckily I'm no Jira Administrator.

Therefore I need to go with the polling option.
Wouldn't I need to track state for inserting entries to events_raw table?
Inserting/recreating incidents table would be easier I think because I could just "dump" all issues with creation and resolved date if available, right?

**Comment by dinagraves** [comment]
That's true -- If you don't have access to the webhook path, your best bet is directly inserting into the incidents table.  I'm assuming you'll always have access to the raw data in JIRA?  Is there a wipeout?  You want to make sure you're maintaining your raw data sufficiently long enough to be able to track progress over time.  

In this case then, you would disable the incidents scheduled query.

**Comment by dinagraves** [comment]
Hi Jo! 

Closing this issue out, but please feel free to share your Jira code!   We started a [Slack channel](https://app.slack.com/client/T0A4R5X0F/C01PUU709V3/details)  if you're interested in discussing further.

-Dina

**Comment by cgriego** [comment]
@dinagraves Where are the instructions for accessing the Slack community? Just using the link above doesn't work and using this link from another issue (https://googlecloud-community.slack.com/archives/fourkeys) requires me to have an @google.com email address, which I don't.

**Comment by dinagraves** [comment]
Oh! Does this work? [https://googlecloud-community.slack.com/channels/fourkeys](https://googlecloud-community.slack.com/channels/fourkeys)

**Comment by cgriego** [comment]
Sadly no, I get the same thing as the link from the other issue. The initial messag is

> You need to sign in to see this page.

Then when I try to create an account and sign in with my Google account (with a gmail email address) I get

> The email address must match one of the domains listed below. Please try another email.

The the domains listed are just google.com

But good news, I get a quick search on Google and found this link which seems to work. https://join.slack.com/t/googlecloud-community/shared_invite/zt-m973j990-IMij2Xh8qKPu7SaHfOcCFg from this page https://cloud.google.com/community

**Comment by dinagraves** [comment]
Thank you! I'll add that to the Contributing page
