### ISSUE TITLE
Data Studio Connector is Unverified

### ISSUE THREAD

**Issue by mikutas** [GoogleCloudPlatform/fourkeys#86]
Today I found I can't browse our dashboards created before.
When opening the dashboards, following pop-up appeared.
<image width=600, src=https://user-images.githubusercontent.com/23391543/109130810-7fa0a900-7795-11eb-9f3a-f2334fe5e409.png />

And clicking "承認(Approval)", then following pop-up appeared.
<image width=400 src=https://user-images.githubusercontent.com/23391543/109131319-0786b300-7796-11eb-91d2-50ff69bc6a69.png />

What happened on "connector" ? (Honestly, I'm not familiar with "connector")
Maybe is it related to "publishing connector" ? -> https://github.com/GoogleCloudPlatform/fourkeys/issues/42#issuecomment-772827518

Or anything wrong with me ?

**Comment by dinagraves** [comment]
Hi! If you previous created a dashboard, you should be able to find it in [datastudio.google.com](https://datastudio.google.com/).

The connector is used for setting up new dashboards.

**Comment by tkms0106** [comment]
I have three dashboards, created on 2020/10/14, 2020/10/21, and 2020/11/24.
Recently I came to be unable to see any data on these all dashboards.
![image](https://user-images.githubusercontent.com/23391543/109480263-ad9c2b00-7abe-11eb-9497-48acba9f2f72.png)

**Comment by dinagraves** [comment]
Ah - Google translated to "Connector approval is required to view this component in the data portal"  

I haven't seen this before.  When did it start?  What happens when you click on "Approve Now"?  Is that the screenshot you shared earlier?  

In the edit view of the dashboard, what happens when you click here?  
<img width="667" alt="Screen Shot 2021-03-01 at 9 19 23 AM" src="https://user-images.githubusercontent.com/55413432/109533775-70f51300-7a6f-11eb-9673-23921bc77ede.png">

It should open up this view of the data connection and if you click Edit Connection, you should be able to reconnect. 
<img width="1489" alt="Screen Shot 2021-03-01 at 9 21 43 AM" src="https://user-images.githubusercontent.com/55413432/109534159-e1039900-7a6f-11eb-8225-c4381e65b317.png">

Then click Reconnect.
<img width="886" alt="Screen Shot 2021-03-01 at 9 22 48 AM" src="https://user-images.githubusercontent.com/55413432/109534174-e4972000-7a6f-11eb-942b-56789c16b395.png">

Can you also confirm that your data is still in BigQuery?  If you go to [the BigQuery Console](http://console.cloud.google.com/bigquery) and select your project, do all the tables have data in them? 

<img width="764" alt="Screen Shot 2021-03-01 at 9 27 00 AM" src="https://user-images.githubusercontent.com/55413432/109534605-5f603b00-7a70-11eb-8b36-5f8332457328.png">

**Comment by tkms0106** [comment]
>In the edit view of the dashboard, what happens when you click here?

Click pencil...
![image](https://user-images.githubusercontent.com/23391543/109581882-79694e80-7b40-11eb-9a90-6212c5bdb7a1.png)

Then, this view appears.
![image](https://user-images.githubusercontent.com/23391543/109582027-bcc3bd00-7b40-11eb-85b5-a1b8e7ca5a97.png)

**Comment by tkms0106** [comment]
>Can you also confirm that your data is still in BigQuery?

Confirmed all of three projects have data in tables(changes/deployments/events_raw).
(We haven't create any incident data yet so incidents table is empty)

**Comment by dinagraves** [comment]
Thank you.  We're working on getting the connector verified.  In the meantime, if you feel confident in doing so, you can click "Advanced" and move forward with authorizing the connector.  The account listed is one of my accounts: `dinagraves@cloudadvocacyorg.joonix.net`

![image](https://user-images.githubusercontent.com/55413432/109730079-c1529a80-7b6d-11eb-8786-e82476f0d0e0.png)

If you do not want to authorize the connector, I have published all of the scripts for the charts in [METRICS.md](https://github.com/GoogleCloudPlatform/fourkeys/blob/main/METRICS.md)

Additionally, I have an open PR with the connector code, so you can review it and decide whether or not you want to authorize the permission.  https://github.com/GoogleCloudPlatform/fourkeys/pull/87/files

**Comment by dinagraves** [comment]
Hi Takumi! Following up to see if this is resolved.  Also would like to invite you to join our [Slack channel]((https://googlecloud-community.slack.com/archives/fourkeys) if you want to chat there and troubleshoot it.

**Comment by tkms0106** [comment]
I was still waiting the connector verified, so I've not tried "Advanced->Go to Four Keys Connectors (unsafe)" yet.

**Comment by dinagraves** [comment]
Hi Takumi,  

I'm afraid I don't know when the connector will be verified.  If you're happy to wait, I'll update this issue when it's verified.  Otherwise, I would recommend using one of the other approaches. 

Best,
Dina

**Comment by tkms0106** [comment]
Still waiting the connector verified, I'm trying BigQuery connector with Custom Query for a while on (a few, not all of) our dashboards, probably it works.

**Comment by sbrudz** [comment]
> Still waiting the connector verified, I'm trying BigQuery connector with [Custom Query](https://github.com/GoogleCloudPlatform/fourkeys/blob/73cceb228d9b4bfde9731f49261aaa7834c67f55/connector/data.gs#L22-L171) for a while on (a few, not all of) our dashboards, ~probably~ it works.

We were starting from scratch and weren't comfortable installing the unverified connector.  We used the following work-around, inspired by the post of @mikutas above (thank you!).

In Google Data Studio:

1. Create a new "Data source"
2. Choose the "BigQuery" connector
3. Choose the custom query option
4. Select fourkeys-xyz as the billing project
5. Paste the contents of `DASHBOARD_QUERY` from `connector/data.gs` into the query box
6. Click the "Connect" button in the top right corner
7. Rename your data source to something memorable

Then to create the dashboard report:

1. Go to: https://datastudio.google.com/reporting/9f328fb6-955f-431b-8761-0eff6e3ae6ed (this is the public read-only template for the four keys dashboard)
2. Click the "Make a copy of this report" button
3. Choose the data source created in the prior section
4. Customize the new dashboard (name, colors, etc.)
5. Click the "View" button
6. Share with co-workers

**Comment by dinagraves** [comment]
Thank you so much for posting these steps!  

I apologize for the delay in the verification.  App Scripts are a bit of an edge case for most of our approvals processes so it's taking some time to navigate our internal systems.

**Comment by frbaron** [comment]
Tried a few weeks ago, and saw the warning above... today, I am totally blocked.

"
This app is blocked
This app tried to access sensitive info in your Google Account. To keep your account safe, Google blocked this access.
"

**Comment by bukecious** [comment]
Hi @dinagraves Please I am having issue with connecting the datasource with App blocked and there is no option for 'advanced' so I can bypass it as advised   . I have used 3 different browsers . What do you advise

**Comment by dinagraves** [comment]
@bukecious  I'm sorry to hear that!  You have a couple options - you can try using the new dashboard in Grafana: https://github.com/GoogleCloudPlatform/fourkeys/pull/204

The datastudio connector is deprecated and the install will no longer redirect to it as soon as this PR is approved and merged.


Alternatively, you can load the script as described here https://github.com/GoogleCloudPlatform/fourkeys/issues/86#issuecomment-823574890

**Comment by bukecious** [comment]
> @bukecious I'm sorry to hear that! You have a couple options - you can try using the new dashboard in Grafana: #204
> 
> The datastudio connector is deprecated and the install will no longer redirect to it as soon as this PR is approved and merged.
> 
> Alternatively, you can load the script as described here [#86 (comment)](https://github.com/GoogleCloudPlatform/fourkeys/issues/86#issuecomment-823574890)

Thank you! I will try it out

**Comment by bukecious** [comment]
> > @bukecious I'm sorry to hear that! You have a couple options - you can try using the new dashboard in Grafana: #204
> > The datastudio connector is deprecated and the install will no longer redirect to it as soon as this PR is approved and merged.
> > Alternatively, you can load the script as described here [#86 (comment)](https://github.com/GoogleCloudPlatform/fourkeys/issues/86#issuecomment-823574890)
> 
> Thank you! I will try it out

Thanks @dinagraves , I used the method by @sbrudz and it worked great . Thanks you both!

**Comment by dinagraves** [comment]
The Grafana dashboards have been added to the installation.  This issue is now obsolete.
