### ISSUE TITLE
help with setup

### ISSUE THREAD

**Issue by ketan-telus** [GoogleCloudPlatform/fourkeys#91]
Hi 4Keys!
My team needs some help setting this up for private repos. What appears to be simple has taken over a week and no success in sight yet. 
Is there anyway one of you can help us out with 30mins of your time?

Ketan

**Comment by davidstanke** [comment]
Hi Ketan! That sounds frustrating. I'd be happy to take a look. Shoot me a DM on twitter (`@davidstanke`) and let's coordinate.

**Comment by davidstanke** [comment]
Follow-up: your colleague Amit reached out and it looks like he's making progress. Closing this. :)
